package norman.gurps.combat.model;

public enum CombatPhase {
    //@formatter:off
    BEGIN_TURN,
    PROMPT_FOR_UNCONSCIOUSNESS_CHECK,
    RESOLVE_UNCONSCIOUSNESS_CHECK,
    PROMPT_FOR_ACTION,
    RESOLVE_ACTION,
    PROMPT_FOR_MELEE_TARGET,
    RESOLVE_MELEE_TARGET,
    PROMPT_FOR_AIM_TARGET,
    RESOLVE_AIM_TARGET,
    PROMPT_FOR_RANGED_TARGET,
    RESOLVE_RANGED_TARGET,
    PROMPT_FOR_TO_HIT,
    RESOLVE_TO_HIT,
    PROMPT_FOR_DEFENSE,
    RESOLVE_DEFENSE,
    PROMPT_FOR_TO_DEFEND,
    RESOLVE_TO_DEFEND,
    PROMPT_FOR_DAMAGE,
    RESOLVE_DAMAGE,
    PROMPT_FOR_DEATH_CHECK,
    RESOLVE_DEATH_CHECK,
    END_TURN
    //@formatter:on
}
