package norman.gurps.combat;

import norman.gurps.combat.model.ActionType;
import norman.gurps.combat.model.ArmorPiece;
import norman.gurps.combat.model.Combatant;
import norman.gurps.combat.model.DamageType;
import norman.gurps.combat.model.GameChar;
import norman.gurps.combat.model.HealthStatus;
import norman.gurps.combat.model.HitLocation;
import norman.gurps.combat.model.MeleeWeapon;
import norman.gurps.combat.model.MeleeWeaponMode;
import norman.gurps.combat.model.ParryType;
import norman.gurps.combat.model.Shield;

import java.util.HashSet;
import java.util.Set;

public class TestHelper {
    public static GameChar getGameChar1() {
        GameChar gameChar = new GameChar();
        gameChar.setName("Bob the Example");
        gameChar.setStrength(14);
        gameChar.setDexterity(13);
        gameChar.setIntelligence(12);
        gameChar.setHealth(11);
        gameChar.setHitPoints(15);
        gameChar.setBasicSpeed(6.25);
        gameChar.setBasicMove(7);
        gameChar.setEncumbranceLevel(1);
        gameChar.setUnconsciousnessCheck(13);
        gameChar.setDeathCheck(12);
        MeleeWeapon weapon = new MeleeWeapon();
        weapon.setName("Broadsword");
        weapon.setSkill(14);
        MeleeWeaponMode swing = new MeleeWeaponMode();
        swing.setName("swing");
        swing.setDamageDice(2);
        swing.setDamageAdds(1);
        swing.setDamageType(DamageType.CUTTING);
        swing.getReaches().add(1);
        weapon.getMeleeWeaponModes().add(swing);
        MeleeWeaponMode thrust = new MeleeWeaponMode();
        thrust.setName("thrust");
        thrust.setDamageDice(1);
        thrust.setDamageAdds(1);
        thrust.setDamageType(DamageType.CRUSHING);
        thrust.getReaches().add(1);
        weapon.getMeleeWeaponModes().add(thrust);
        weapon.setParryType(ParryType.YES);
        weapon.setParryModifier(0);
        weapon.setMinStrength(10);
        weapon.setTwoHanded(false);
        gameChar.getMeleeWeapons().add(weapon);
        Shield shield = new Shield();
        shield.setName("Medium Shield");
        shield.setSkill(13);
        shield.setDefenseBonus(2);
        gameChar.getShields().add(shield);
        ArmorPiece torso = new ArmorPiece();
        torso.setHitLocation(HitLocation.TORSO);
        torso.setDamageResistance(1);
        gameChar.getArmorPieces().add(torso);
        ArmorPiece groin = new ArmorPiece();
        groin.setHitLocation(HitLocation.GROIN);
        groin.setDamageResistance(1);
        gameChar.getArmorPieces().add(groin);
        ArmorPiece legs = new ArmorPiece();
        legs.setHitLocation(HitLocation.LEGS);
        legs.setDamageResistance(1);
        gameChar.getArmorPieces().add(legs);
        ArmorPiece arms = new ArmorPiece();
        arms.setHitLocation(HitLocation.ARMS);
        arms.setDamageResistance(1);
        gameChar.getArmorPieces().add(arms);
        ArmorPiece skull = new ArmorPiece();
        skull.setHitLocation(HitLocation.SKULL);
        skull.setDamageResistance(1);
        gameChar.getArmorPieces().add(skull);
        ArmorPiece face = new ArmorPiece();
        face.setHitLocation(HitLocation.FACE);
        face.setDamageResistance(1);
        gameChar.getArmorPieces().add(face);
        ArmorPiece hands = new ArmorPiece();
        hands.setHitLocation(HitLocation.HANDS);
        hands.setDamageResistance(1);
        gameChar.getArmorPieces().add(hands);
        ArmorPiece feet = new ArmorPiece();
        feet.setHitLocation(HitLocation.FEET);
        feet.setDamageResistance(1);
        gameChar.getArmorPieces().add(feet);
        return gameChar;
    }

    public static GameChar getGameChar2() {
        GameChar gameChar = new GameChar();
        gameChar.setName("Grunt");
        gameChar.setStrength(10);
        gameChar.setDexterity(10);
        gameChar.setIntelligence(10);
        gameChar.setHealth(10);
        gameChar.setHitPoints(10);
        gameChar.setBasicSpeed(5.0);
        gameChar.setBasicMove(5);
        gameChar.setEncumbranceLevel(2);
        gameChar.setUnconsciousnessCheck(10);
        gameChar.setDeathCheck(10);
        MeleeWeapon weapon = new MeleeWeapon();
        weapon.setName("Broadsword");
        weapon.setSkill(12);
        MeleeWeaponMode swing = new MeleeWeaponMode();
        swing.setName("swing");
        swing.setDamageDice(1);
        swing.setDamageAdds(1);
        swing.setDamageType(DamageType.CUTTING);
        swing.getReaches().add(1);
        weapon.getMeleeWeaponModes().add(swing);
        MeleeWeaponMode thrust = new MeleeWeaponMode();
        thrust.setName("thrust");
        thrust.setDamageDice(1);
        thrust.setDamageAdds(-1);
        thrust.setDamageType(DamageType.CRUSHING);
        thrust.getReaches().add(1);
        weapon.getMeleeWeaponModes().add(thrust);
        weapon.setParryType(ParryType.YES);
        weapon.setParryModifier(0);
        weapon.setMinStrength(10);
        weapon.setTwoHanded(false);
        gameChar.getMeleeWeapons().add(weapon);
        Shield shield = new Shield();
        shield.setName("Medium Shield");
        shield.setSkill(10);
        shield.setDefenseBonus(2);
        gameChar.getShields().add(shield);
        ArmorPiece torso = new ArmorPiece();
        torso.setHitLocation(HitLocation.TORSO);
        torso.setDamageResistance(2);
        gameChar.getArmorPieces().add(torso);
        ArmorPiece groin = new ArmorPiece();
        groin.setHitLocation(HitLocation.GROIN);
        groin.setDamageResistance(2);
        gameChar.getArmorPieces().add(groin);
        ArmorPiece legs = new ArmorPiece();
        legs.setHitLocation(HitLocation.LEGS);
        legs.setDamageResistance(2);
        gameChar.getArmorPieces().add(legs);
        ArmorPiece arms = new ArmorPiece();
        arms.setHitLocation(HitLocation.ARMS);
        arms.setDamageResistance(2);
        gameChar.getArmorPieces().add(arms);
        ArmorPiece skull = new ArmorPiece();
        skull.setHitLocation(HitLocation.SKULL);
        skull.setDamageResistance(2);
        gameChar.getArmorPieces().add(skull);
        ArmorPiece face = new ArmorPiece();
        face.setHitLocation(HitLocation.FACE);
        face.setDamageResistance(2);
        gameChar.getArmorPieces().add(face);
        ArmorPiece hands = new ArmorPiece();
        hands.setHitLocation(HitLocation.HANDS);
        hands.setDamageResistance(2);
        gameChar.getArmorPieces().add(hands);
        ArmorPiece feet = new ArmorPiece();
        feet.setHitLocation(HitLocation.FEET);
        feet.setDamageResistance(2);
        gameChar.getArmorPieces().add(feet);
        return gameChar;
    }

    public static Combatant getCombatant(GameChar gameChar) {
        Set<String> existingLabels = new HashSet<>();
        return getCombatant(gameChar, existingLabels);
    }

    public static Combatant getCombatant(GameChar gameChar, Set<String> existingLabels) {
        Combatant combatant = new Combatant(gameChar, existingLabels);
        combatant.setCurrentDamage(0);
        combatant.setPreviousDamage(0);
        combatant.setUnconsciousnessCheckFailed(false);
        combatant.setNbrOfDeathChecksNeeded(0);
        combatant.setDeathCheckFailed(false);
        combatant.setHealthStatus(HealthStatus.ALIVE);
        int basicMove = combatant.getGameChar().getBasicMove();
        int encumbranceLevel = combatant.getGameChar().getEncumbranceLevel();
        combatant.setCurrentMove(basicMove - encumbranceLevel);
        combatant.setActionType(ActionType.DO_NOTHING);
        return combatant;
    }
}
